services:
  densitydata:
    container_name: densitydata
    image: silvertetris/densitydata:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - KOSIS_API_TOKEN=your_api_token_here
